Feature/css setting
mhsiungw/simple-twitter-front-end pull request #17
Opened 2022-12-09 02:45 UTC by Beginneraboutlife116

主要是將一些色卡、字體大小跟reset CSS放上去，改成用SCSS的形式使用。
大部分的SCSS 變數都放在abstract中，另外base裡面放入reset CSS跟一些基本的base設定。
包含字體大小、字體顏色、基本會用到的顏色等等。

最後把他們彙整到 `:root` 上面去，並且用語意化的方式呈現每一個CSS custom properties，以利大家使用。
命名可以在開會時再討論

2022-12-16 13:29 UTC, chacowang0125 approved these changes

2023-03-05 01:31 UTC, mhsiungw requested changes

2023-03-05 01:31 UTC, mhsiungw commented on src/styles/variables.scss
> +$fz-900: 19px;
最底下記得留一行

2023-03-07 18:05 UTC, Beginneraboutlife116 commented on src/styles/variables.scss
> +$fz-900: 19px;
好

2023-03-12 02:03 UTC, mhsiungw approved these changes

2023-03-12 02:47 UTC, chacowang0125 approved these changes

2023-03-12 03:05 UTC, merged