free validator for developers to return multiple error message
mhsiungw/simple-twitter-front-end pull request #29
Opened 2023-03-19 04:27 UTC by Beginneraboutlife116

現在可以單純經由validator的邏輯判斷傳出錯誤訊息。
但空格的錯誤訊息仍建議使用submit去調整

2023-04-25 07:10 UTC, mhsiungw requested changes

2023-04-25 07:10 UTC, mhsiungw commented on src/components/form/components/form-item/index.tsx
> +	rule?: (targetValue: string) => string | "",
用空字串代表沒有錯誤好像不夠語意化，或許用 null?
![Screenshot 2023-04-25 at 3 10 32 PM](https://user-images.githubusercontent.com/81913228/234201004-03220316-79f5-4edd-b5e4-1cd1db5df30e.jpg)

2023-04-26 00:50 UTC, Beginneraboutlife116 commented on src/components/form/components/form-item/index.tsx
> +	rule?: (targetValue: string) => string | "",
OK

2023-04-26 03:18 UTC, mhsiungw approved these changes

2023-04-27 02:00 UTC, merged